// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using delivery.Repositories;

#nullable disable

namespace delivery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825151927_TablasAuxiliares")]
    partial class TablasAuxiliares
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("delivery.Models.Articulo", b =>
                {
                    b.Property<int>("CodArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodArticulo"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Stock")
                        .HasColumnType("smallint");

                    b.Property<short?>("StockMinimo")
                        .HasColumnType("smallint");

                    b.HasKey("CodArticulo");

                    b.ToTable("articulos");
                });

            modelBuilder.Entity("delivery.Models.Cliente", b =>
                {
                    b.Property<int>("CodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCliente"));

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasKey("CodCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("delivery.Models.DetallePedido", b =>
                {
                    b.Property<int>("NroPedido")
                        .HasColumnType("int");

                    b.Property<int>("CodPromo")
                        .HasColumnType("int");

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PreUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NroPedido", "CodPromo");

                    b.HasIndex("CodPromo");

                    b.ToTable("detalles_pedido");
                });

            modelBuilder.Entity("delivery.Models.DetallePromo", b =>
                {
                    b.Property<int>("CodPromo")
                        .HasColumnType("int");

                    b.Property<int>("CodArticulo")
                        .HasColumnType("int");

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.HasKey("CodPromo", "CodArticulo");

                    b.HasIndex("CodArticulo");

                    b.ToTable("detalle_promos");
                });

            modelBuilder.Entity("delivery.Models.FormaPago", b =>
                {
                    b.Property<int>("CodFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFormaPago"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodFormaPago");

                    b.ToTable("formas_pago");
                });

            modelBuilder.Entity("delivery.Models.Pedido", b =>
                {
                    b.Property<int>("Nro_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nro_pedido"));

                    b.Property<int>("Cod_cliente")
                        .HasColumnType("int");

                    b.Property<string>("DireccionEnvio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Nro_pedido");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("delivery.Models.Promo", b =>
                {
                    b.Property<int>("CodPromo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPromo"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodPromo");

                    b.ToTable("promos");
                });

            modelBuilder.Entity("delivery.Models.TipoEnvio", b =>
                {
                    b.Property<int>("CodTipoEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoEnvio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodTipoEnvio");

                    b.ToTable("tipos_envio");
                });

            modelBuilder.Entity("delivery.Models.DetallePedido", b =>
                {
                    b.HasOne("delivery.Models.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("CodPromo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("delivery.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("NroPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("delivery.Models.DetallePromo", b =>
                {
                    b.HasOne("delivery.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("CodArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("delivery.Models.Promo", "Promo")
                        .WithMany("DetallePromos")
                        .HasForeignKey("CodPromo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("delivery.Models.Promo", b =>
                {
                    b.Navigation("DetallePromos");
                });
#pragma warning restore 612, 618
        }
    }
}
