// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using delivery.Repositories;

#nullable disable

namespace delivery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913175453_AgregaGustosYDetalles")]
    partial class AgregaGustosYDetalles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("delivery.Data.Models.ConfiguracionLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMaps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TarifaEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesLocales");
                });

            modelBuilder.Entity("delivery.Models.Articulo", b =>
                {
                    b.Property<int>("CodArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodArticulo"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CodRubro")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxGustos")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodArticulo");

                    b.HasIndex("CategoriaId");

                    b.ToTable("articulos");
                });

            modelBuilder.Entity("delivery.Models.Banner", b =>
                {
                    b.Property<int>("CodBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodBanner"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodBanner");

                    b.ToTable("banners");
                });

            modelBuilder.Entity("delivery.Models.Categoria", b =>
                {
                    b.Property<int>("CodCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCategoria"));

                    b.Property<int?>("BannerId")
                        .HasColumnType("int");

                    b.Property<int>("CodRubro")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodCategoria");

                    b.HasIndex("BannerId");

                    b.HasIndex("CodRubro");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("delivery.Models.Cliente", b =>
                {
                    b.Property<int>("CodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCliente"));

                    b.Property<string>("Cuit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cuit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreLocal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre_local");

                    b.HasKey("CodCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("delivery.Models.DetallePedido", b =>
                {
                    b.Property<int>("CodDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodDetalle"));

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.Property<int?>("CodArticulo")
                        .HasColumnType("int");

                    b.Property<int>("CodPedido")
                        .HasColumnType("int");

                    b.Property<int?>("CodPromo")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodDetalle");

                    b.HasIndex("CodArticulo");

                    b.HasIndex("CodPedido");

                    b.HasIndex("CodPromo");

                    b.ToTable("detalle_pedidos");
                });

            modelBuilder.Entity("delivery.Models.DetallePromo", b =>
                {
                    b.Property<int>("CodPromo")
                        .HasColumnType("int");

                    b.Property<int>("CodArticulo")
                        .HasColumnType("int");

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.HasKey("CodPromo", "CodArticulo");

                    b.HasIndex("CodArticulo");

                    b.ToTable("detalle_promos");
                });

            modelBuilder.Entity("delivery.Models.FormaPago", b =>
                {
                    b.Property<int>("CodFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFormaPago"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodFormaPago");

                    b.ToTable("formas_pago");
                });

            modelBuilder.Entity("delivery.Models.Gusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HayStock")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("gustos");
                });

            modelBuilder.Entity("delivery.Models.ImagenArticulo", b =>
                {
                    b.Property<int>("CodImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodImagen"));

                    b.Property<int>("CodArticulo")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodImagen");

                    b.HasIndex("CodArticulo");

                    b.ToTable("imagenes_articulos");
                });

            modelBuilder.Entity("delivery.Models.Pedido", b =>
                {
                    b.Property<int>("CodPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPedido"));

                    b.Property<int>("CodCliente")
                        .HasColumnType("int");

                    b.Property<int>("CodFormaPago")
                        .HasColumnType("int");

                    b.Property<int>("CodTipoEnvio")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodPedido");

                    b.HasIndex("CodCliente");

                    b.HasIndex("CodFormaPago");

                    b.HasIndex("CodTipoEnvio");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("delivery.Models.Promo", b =>
                {
                    b.Property<int>("CodPromo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPromo"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodPromo");

                    b.ToTable("promos");
                });

            modelBuilder.Entity("delivery.Models.Rubro", b =>
                {
                    b.Property<int>("CodRubro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodRubro"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodRubro");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("delivery.Models.TarifaEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("tarifa_envio");
                });

            modelBuilder.Entity("delivery.Models.TipoEnvio", b =>
                {
                    b.Property<int>("CodTipoEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoEnvio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodTipoEnvio");

                    b.ToTable("tipos_envio");
                });

            modelBuilder.Entity("delivery.Models.Articulo", b =>
                {
                    b.HasOne("delivery.Models.Categoria", "Categoria")
                        .WithMany("Articulos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("delivery.Models.Categoria", b =>
                {
                    b.HasOne("delivery.Models.Banner", "Banner")
                        .WithMany()
                        .HasForeignKey("BannerId");

                    b.HasOne("delivery.Models.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("CodRubro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banner");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("delivery.Models.DetallePedido", b =>
                {
                    b.HasOne("delivery.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("CodArticulo");

                    b.HasOne("delivery.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("CodPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("delivery.Models.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("CodPromo");

                    b.Navigation("Articulo");

                    b.Navigation("Pedido");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("delivery.Models.DetallePromo", b =>
                {
                    b.HasOne("delivery.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("CodArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("delivery.Models.Promo", "Promo")
                        .WithMany("DetallePromos")
                        .HasForeignKey("CodPromo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("delivery.Models.ImagenArticulo", b =>
                {
                    b.HasOne("delivery.Models.Articulo", "Articulo")
                        .WithMany("ImagenesExtras")
                        .HasForeignKey("CodArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("delivery.Models.Pedido", b =>
                {
                    b.HasOne("delivery.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CodCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("delivery.Models.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("CodFormaPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("delivery.Models.TipoEnvio", "TipoEnvio")
                        .WithMany()
                        .HasForeignKey("CodTipoEnvio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("FormaPago");

                    b.Navigation("TipoEnvio");
                });

            modelBuilder.Entity("delivery.Models.Articulo", b =>
                {
                    b.Navigation("ImagenesExtras");
                });

            modelBuilder.Entity("delivery.Models.Categoria", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("delivery.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("delivery.Models.Promo", b =>
                {
                    b.Navigation("DetallePromos");
                });
#pragma warning restore 612, 618
        }
    }
}
